# Generated by Django 2.1 on 2018-08-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration_months', models.PositiveIntegerField()),
                ('employee_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSchool',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration_years', models.PositiveIntegerField()),
                ('employee_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('employee_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration_months', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='skill_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='employee.Skill'),
        ),
        migrations.AddField(
            model_name='employeeschool',
            name='school_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='employee.School'),
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='project_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='employee.Project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(
                through='employee.EmployeeProject', to='employee.Project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='school',
            field=models.ManyToManyField(
                through='employee.EmployeeSchool', to='employee.School'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(
                through='employee.EmployeeSkill', to='employee.Skill'),
        ),
    ]
