# Generated by Django 2.1 on 2018-08-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employeeproject_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
