# Generated by Django 2.1 on 2018-08-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20180823_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeproject',
            name='skills',
            field=models.ManyToManyField(to='employee.Skill'),
        ),
    ]
