# Generated by Django 2.1 on 2018-08-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20180827_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskill',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
