# Generated by Django 2.1 on 2018-09-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employee_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeproject',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
