# Generated by Django 2.1 on 2018-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employeeproject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
