# Generated by Django 2.1 on 2018-09-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0015_auto_20180912_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'skill_categories',
            },
        ),
        migrations.RunSQL(
            """
            INSERT INTO `skill_categories` (name) 
            values ('OS'), 
            ('Languages'), 
            ('Technologies and platforms'), 
            ('DBMS'), 
            ('IDEs'), 
            ('Versioning'), 
            ('Issue Management'), 
            ('Methodologies')
            """),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE,
                                    to='employee.SkillCategory'),
        ),
    ]
