# Generated by Django 2.1 on 2018-09-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20180913_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='carrier_start_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
