# Generated by Django 2.1 on 2018-09-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20180927_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='carrier_start_date',
            new_name='career_start_date',
        ),
    ]
