# Generated by Django 2.1 on 2019-01-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20190129_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
