# Generated by Django 2.1 on 2019-05-21 08:39

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_employeefile_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='file',
            field=models.FileField(upload_to=employee.models.employee_directory_path),
        ),
    ]
