# Generated by Django 2.1 on 2019-05-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_auto_20190523_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_finished',
            field=models.BooleanField(default=True),
        ),
    ]
