# Generated by Django 2.1 on 2019-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20190524_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeproject',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
