# Generated by Django 2.1 on 2020-06-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_project_image'),
        ('employee', '0025_auto_20190524_1227'),
    ]

    operations = [
    ]
