export * from './loading/loadingMain'
export * from './login/login'
export * from './home/home'
export * from './register/register'
export * from './profile/profile'
export * from './projects/projects'