export const LOGIN_ERRORS = 'LOGIN_ERRORS';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const REGISTER_ERRORS = 'REGISTER_ERRORS';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const SET_USER = 'SET_USER';