//Boolean fields
export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const IS_STAFF = 'IS_STAFF';

//Set boolean fields for modal windows
export const SET_SKILL_MODAL = 'SET_SKILL_MODAL';
export const SET_SCHOOL_MODAL = 'SET_SCHOOL_MODAL';
export const SET_PROJECT_MODAL = 'SET_PROJECT_MODAL';
export const SET_TEAM_MODAL = 'SET_TEAM_MODAL';
export const SET_PASSWORD_MODAL = 'SET_PASSWORD_MODAL';

//Set operations
export const SET_USER = 'SET_USER';
export const SET_SKILL = 'SET_SKILL';
export const SET_SKILLS = 'SET_SKILLS';
export const SET_SKILL_CATEGORIES = 'SET_SKILL_CATEGORIES';
export const SET_SCHOOL = 'SET_SCHOOL';
export const SET_SCHOOLS = 'SET_SCHOOLS';
export const SET_PROJECT = 'SET_PROJECT';
export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_USER_PROJECTS = 'SET_USER_PROJECTS';
export const SET_USER_SKILLS = 'SET_USER_SKILLS';
export const SET_USER_SCHOOLS = 'SET_USER_SCHOOLS';
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const SET_EMPLOYEE = 'SET_EMPLOYEE';
export const SET_EMPLOYEE_FILES = 'SET_EMPLOYEE_FILES';

//Loadings
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const NEW_SKILL_LOADING = 'NEW_SKILL_LOADING';
export const NEW_SCHOOL_LOADING = 'NEW_SCHOOL_LOADING';
export const NEW_PROJECT_LOADING = 'NEW_PROJECT_LOADING';
export const NEW_USER_PROJECT_LOADING = 'NEW_USER_PROJECT_LOADING';
export const NEW_USER_SKILL_LOADING = 'NEW_USER_SKILL_LOADING';
export const NEW_USER_SCHOOL_LOADING = 'NEW_USER_SCHOOL_LOADING';
export const EDIT_USER_LOADING = 'EDIT_USER_LOADING';
export const EDIT_USER_PHOTO_LOADING = 'EDIT_USER_PHOTO_LOADING';

//Errors
export const LOGIN_ERRORS = 'LOGIN_ERRORS';
export const REGISTER_ERRORS = 'REGISTER_ERRORS';
export const CREATE_SKILL_ERRORS = 'CREATE_SKILL_ERRORS';
export const CREATE_SCHOOL_ERRORS = 'CREATE_SCHOOL_ERRORS';
export const CREATE_PROJECT_ERRORS = 'CREATE_PROJECT_ERRORS';
export const CREATE_USER_PROJECT_ERRORS = 'CREATE_USER_PROJECT_ERRORS';
export const CREATE_USER_SKILL_ERRORS = 'CREATE_USER_SKILL_ERRORS';
export const CREATE_USER_SCHOOL_ERRORS = 'CREATE_USER_SCHOOL_ERRORS';
export const EDIT_USER_ERRORS = 'EDIT_USER_ERRORS';
export const EMPLOYEE_FILES_ERRORS = 'EMPLOYEE_FILES_ERRORS';

//Add to existing arrays actions
export const ADD_SKILL = 'ADD_SKILL';
export const ADD_SCHOOL = 'ADD_SCHOOL';
export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_USER_PROJECT = 'ADD_USER_PROJECT';
export const ADD_USER_SKILL = 'ADD_USER_SKILL';
export const ADD_USER_SCHOOL = 'ADD_USER_SCHOOL';
export const ADD_PROJECT_FILE = 'ADD_PROJECT_FILE';
export const ADD_EMPLOYEE_FILE = 'ADD_EMPLOYEE_FILE';

//Delete actions
export const DELETE_USER_PROJECT = 'DELETE_USER_PROJECT';
export const DELETE_USER_SKILL = 'DELETE_USER_SKILL';
export const DELETE_USER_SCHOOL = 'DELETE_USER_SCHOOL';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_SKILL = 'DELETE_SKILL';
export const DELETE_SCHOOL = 'DELETE_SCHOOL';

//Edit actions
export const CHANGE_USER_PROJECT = 'CHANGE_USER_PROJECT';
export const CHANGE_USER_SKILL = 'CHANGE_USER_SKILL';
export const CHANGE_USER_SCHOOL = 'CHANGE_USER_SCHOOL';
export const CHANGE_PROJECT = 'CHANGE_PROJECT';
export const CHANGE_SKILL = 'CHANGE_SKILL';
export const CHANGE_SCHOOL = 'CHANGE_SCHOOL';

//Success actions
export const SUCCESSFUL_EDIT_USER_PROJECT = 'SUCCESSFUL_EDIT_USER_PROJECT';
export const SUCCESSFUL_EDIT_USER_SKILL = 'SUCCESSFUL_EDIT_USER_SKILL';
export const SUCCESSFUL_EDIT_USER_SCHOOL = 'SUCCESSFUL_EDIT_USER_SCHOOL';
export const SUCCESSFUL_EDIT_USER = 'SUCCESSFUL_EDIT_USER';
export const SUCCESSFUL_EDIT_PROJECT = 'SUCCESSFUL_EDIT_PROJECT';
export const SUCCESSFUL_EDIT_SKILL = 'SUCCESSFUL_EDIT_SKILL';
export const SUCCESSFUL_EDIT_SCHOOL = 'SUCCESSFUL_EDIT_SCHOOL';

//remove actions
export const REMOVE_USER_SKILL_ERRORS = 'REMOVE_USER_SKILL_ERRORS';
export const REMOVE_USER_SCHOOL_ERRORS = 'REMOVE_USER_SCHOOL_ERRORS';
export const REMOVE_USER_ERRORS = 'REMOVE_USER_ERRORS';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const REMOVE_PROJECT_FILE = 'REMOVE_PROJECT_FILE';
export const REMOVE_EMPLOYEE_FILE = 'REMOVE_EMPLOYEE_FILE';